
png(file='plot4.png')
par(mfrow=c(2,2))
plot(data$Timestamp, data$Global_active_power, type='l', ylab='Global Active Power (kilowatts)', xlab='')
plot(data$Timestamp, data$Voltage, type='l', ylab='Voltage', xlab='datetime')
plot(data$Timestamp, data$Sub_metering_1, type='n', ylab='Energy sub metering', xlab='')
lines(data$Timestamp, data$Sub_metering_1)
lines(data$Timestamp, data$Sub_metering_2, col='red')
lines(data$Timestamp, data$Sub_metering_3, col='blue')
legend('topright', lty=c(1,1,1),col=c('black', 'red', 'blue'), legend=c('Sub_metering_1','Sub_metering_2','Sub_metering_3'))
plot(data$Timestamp, data$Global_reactive_power, type='l', ylab='Global_reactive_power', xlab='datetime')
dev.off()